
site_name: Atlas Coder DSPy v6
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github-alt
repo_url: https://github.com/your-repo/atlas-coder
repo_name: your-repo/atlas-coder
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Workflows: workflows.md
  - Contributing: contributing.md
