name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,docs]

    - name: Run Black (code formatter)
      run: black --check .

    - name: Run Ruff (linter)
      run: ruff check .

    - name: Run MyPy (type checker)
      run: mypy atlas_coder/

    - name: Run Pytest (unit and integration tests)
      run: pytest tests/

    - name: Run Demo Scripts (if any)
      run: |
        # Add commands to run demo scripts here, e.g.:
        # python examples/basic_usage.py
        echo "No demo scripts configured yet."
